#include <math.h>

#define TRANSMISSION_RATIO 120
#define ENCODER_TICKS 32
#define TICKS_PER_REV (ENCODER_TICKS * TRANSMISSION_RATIO)
#define WHEEL_CIRCUMFERENCE 0.214
#define MM_PER_TICK ((float) (WHEEL_CIRCUMFERENCE) / TICKS_PER_REV)
#define RAD_PER_TICK (2 * M_PI / TICKS_PER_REV)
#define MAX_VELOCITY 2
#define SECS_TO_MICROS pow(10, 6)
