#include <math.h>

#define TRANSMISSION_RATIO 120
#define ENCODER_TICKS 32
#define TICKS_PER_WHEEL_REVOLUTION ENCODER_TICKS * TRANSMISSION_RATIO
#define WHEEL_CIRCUMFERENCE 214
#define MM_PER_TICK (float)(WHEEL_CIRCUMFERENCE) / TICKS_PER_WHEEL_REVOLUTION
#define RAD_PER_TICK (2 * M_PI) / TICKS_PER_WHEEL_REVOLUTION
