#define TRANSMISSION_RATIO 120
#define ENCODER_TICKS 32
#define TICKS_PER_WHEEL_REVOLUTION ENCODER_TICKS * TRANSMISSION_RATIO
#define WHEEL_CIRCUMFERENCE 214
#define TICK_PER_MM TICKS_PER_WHEEL_REVOLUTION / WHEEL_CIRCUMFERENCE
